--Assignment 1.1
--xóa bản sao trong cột user_id
SELECT DISTINCT USER_ID 
FROM FACT_APP_EVENT
--đổi cột created_at từ định dạng nvarchar thành date
ALTER TABLE FACT_APP_EVENT
ALTER COLUMN CREATED_AT DATE
--lấy ra tổng số lượt Click trong một ngày
SELECT CREATED_AT AS THOI_GIAN, SUM(CLICK) AS TONG_CLICK
FROM FACT_APP_EVENT
GROUP BY CREATED_AT
ORDER BY CREATED_AT
--lấy ra tổng số lượt Click trong một tháng 
SELECT MONTH(CREATED_AT) AS THOI_GIAN, SUM(CLICK) AS TONG_CLICK
FROM FACT_APP_EVENT
GROUP BY MONTH(CREATED_AT)
ORDER BY MONTH(CREATED_AT)
--Assignment 1.2.1 
--đếm số người dùng theo khu vực 
SELECT LOCATION, COUNT(USER_ID) AS SO_NGUOI_DUNG
FROM FACT_APP_EVENT
GROUP BY LOCATION
ORDER BY LOCATION
--Assignment 1.2.2
--tính chỉ số CTR theo tháng
SELECT MONTH(CREATED_AT) AS THOI_GIAN, SUM(CLICK)/SUM(IMPRESSION)*100 AS CTR
FROM FACT_APP_EVENT
GROUP BY MONTH(CREATED_AT)
ORDER BY MONTH(CREATED_AT)
--Assignment 1.2.3
--Thời gian ở lại trên mỗi lần Click của khách hàng theo khu vực 
SELECT LOCATION, SUM(IMPRESSION)/SUM(CLICK) AS GIAY
FROM FACT_APP_EVENT
GROUP BY LOCATION
ORDER BY LOCATION
--Assignment 2
--đổi cột registered_date từ định dạng datetime thành date
ALTER TABLE DIM_USER_PROFILE
ALTER COLUMN registered_date DATE
--Assignment 2.1
--tổng số khách hàng theo khu vực
SELECT LOCATION, COUNT(USER_ID) AS SO_NGUOI_DUNG
FROM DIM_USER_PROFILE
GROUP BY LOCATION
ORDER BY LOCATION
--Assignment 2.2.1
--tính tổng giá trị giao dịch theo địa lý
SELECT LOCATION, SUM(TOTAL_TRANSACTION_VALUE_VND) AS TONG_GIA_TRI
FROM DIM_USER_PROFILE
GROUP BY LOCATION
ORDER BY LOCATION
--Assignment 2.2.2
--số người giao dịch tính theo danh mục chính
SELECT MAIN_CATEGORY, COUNT(USER_ID) AS SO_NGUOI_DUNG_MAIN
FROM DIM_USER_PROFILE
GROUP BY MAIN_CATEGORY
ORDER BY MAIN_CATEGORY
--số người giao dịch tính theo danh mục phụ
SELECT SECONDARY_CATEGORY, COUNT(USER_ID) AS SO_NGUOI_DUNG_SECONDARY
FROM DIM_USER_PROFILE
GROUP BY SECONDARY_CATEGORY
ORDER BY SECONDARY_CATEGORY
--Assignment 2.2.3 
--tổng giá trị giao dịch theo danh mục chính
SELECT MAIN_CATEGORY, SUM(TOTAL_TRANSACTION_VALUE_VND) AS TONG_GIA_TRI
FROM DIM_USER_PROFILE
GROUP BY MAIN_CATEGORY
ORDER BY MAIN_CATEGORY








